### ISSUE TITLE
可以提供个针对全局的 jvm 配置吗

### ISSUE THREAD

**Issue by codecly259** [huzunrong/jvm-parameter-intellij-plugin#1]
现在jvm参数配置都是只针对当前 project 有效的，因为有时候会打开好几个 project, 希望可以提供一个全局的 jvm 参数配置，对所有 project 都有效

**Comment by codecly259** [comment]
已经参考这个代码重新实现了一个插件，多谢作者提供这个插件的源码，如有侵权，请联系删除

**Comment by newhoo** [comment]
全局实际使用场景少。Idea本身就支持设置为全局，在idea的欢迎页面保存的参数对所有打开的项目有效。

**Comment by newhoo** [comment]
1.0.3已经支持全局参数了，可以试试
