### ISSUE TITLE
全局配置和Run Configurations下的优先级

### ISSUE THREAD

**Issue by ninggc** [huzunrong/jvm-parameter-intellij-plugin#2]
运行时，全局配置的好像被追加到Run Configurations的配置后面了，导致Run Configurations的jvm配置被覆盖。

是否可以改变一下顺序？

**Comment by newhoo** [comment]
全局配置是指勾选了Global吗？Run Configurations是指IDEA本身的一次run吗？IDEA提供的API有限，如果不想被覆盖，可以不勾选ENABLE
