### ISSUE TITLE
希望预览可以展开

### ISSUE THREAD

**Issue by lians0** [huzunrong/jvm-parameter-intellij-plugin#4]
像是配置运行里的jvm参数一样
![image](https://github.com/newhoo/jvm-parameter-intellij-plugin/assets/30581350/22e145cf-ec24-41ad-8d90-950b3c98812d)

![image](https://github.com/newhoo/jvm-parameter-intellij-plugin/assets/30581350/e60d0c2f-dc67-413e-9fde-311aa4c45e0f)

**Comment by newhoo** [comment]
可以，我研究一下

**Comment by newhoo** [comment]
重新看了下，鼠标在预览文本框hover就能看到展开内容。另外，jvm参数生成规则比较统一，根据下面表格内容也能看得出。
