### ISSUE TITLE
global有什么作用，好像readme中并没有说明

### ISSUE THREAD

**Issue by aierx** [huzunrong/jvm-parameter-intellij-plugin#5]

**Comment by newhoo** [comment]
global作用：A项目设置的参数在其他项目也能看到及使用

**Comment by aierx** [comment]
明白了，感谢大佬。
我还有这样一种需求，比如我想在idea中启动springboot项目需要引入额外的jar包，但是我有不想改动pom文件（因为这个包只在调试时候使用）或者添加到依赖（因为添加依赖，刷新一下maven就没了）。如果我去指定classpath的话，会将之前idea的classpath覆盖掉，不知道有没有插件可以做到。

**Comment by newhoo** [comment]
> 明白了，感谢大佬。
> 我还有这样一种需求，比如我想在idea中启动springboot项目需要引入额外的jar包，但是我有不想改动pom文件（因为这个包只在调试时候使用）或者添加到依赖（因为添加依赖，刷新一下maven就没了）。如果我去指定classpath的话，会将之前idea的classpath覆盖掉，不知道有没有插件可以做到。

好像没有现成的插件，可以通过Javaagent实现，思路如下：编写一个Javaagent，逻辑比较简单就是把你需要的jar复制到classpath中，然后agent打成jar包，在我这个插件中配置agent启动参数。如果设置正确，那么启动时就会执行agent逻辑。你可以试试，agent实现可以参考https://github.com/newhoo/mysql-explain/tree/master/mysql-explain-agent

**Comment by aierx** [comment]
感谢🙏
