### ISSUE TITLE
希望能够添加备注信息

### ISSUE THREAD

**Issue by niejp2024** [huzunrong/jvm-parameter-intellij-plugin#6]
![mmexport1726197185600](https://github.com/user-attachments/assets/ade7cab6-cabd-4988-a395-c88beb4d46a5)
开发中环境不同时需要不同参数，希望有备注记录下是哪个环境的

**Comment by newhoo** [comment]
暂时没有计划添加这个，勉强可以这样实现：在相邻行添加描述信息的同时不勾选。

另外，这个插件的功能已经合并到 [RestfulBox](https://github.com/newhoo/RestfulBox) 中，同时支持运行环境管理，功能更强大，欢迎体验

![图片](https://github.com/user-attachments/assets/90be2e54-a5d9-4f04-8e14-857894f2e7f0)
